repos:
  - repo: local
    hooks:
    - id: black
      name: black
      stages: [commit]
      language: system
      entry: python -m black
      args: [picasso]
      types: [python]

    - id: isort
      name: isort
      stages: [commit]
      language: system
      entry: python -m isort
      args: [-rc, picasso]
      types: [python]
